- name: Configure NGINX
  hosts: all
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Configure NGINX reverse proxy
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://localhost:8080;
              }
          }

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted
