---
- name: Setup Monitoring Stack (Node Exporter + Prometheus + Grafana)
  hosts: all
  become: yes
  vars:
    prometheus_dir: /opt/monitoring
    grafana_admin_password: "ChangeMe123!"
  tasks:

    - name: Ensure apt package index is updated
      raw: apt-get update -y
      register: update_result
      changed_when: "'0 upgraded' not in update_result.stdout"
      ignore_errors: yes

    - name: Install dependencies
      raw: apt-get install -y ca-certificates curl gnupg lsb-release docker.io docker-compose
      register: install_result
      changed_when: "'installed' in install_result.stdout or 'newly installed' in install_result.stdout"
      ignore_errors: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create monitoring directory
      file:
        path: "{{ prometheus_dir }}"
        state: directory
        mode: '0755'

    - name: Create Prometheus config
      template:
        src: ../Roles/Templates/prometheus.yml.j2
        dest: "{{ prometheus_dir }}/prometheus.yml"
        mode: '0644'

    - name: Create Grafana provisioning directories
      file:
        path: "{{ prometheus_dir }}/grafana/provisioning/datasources"
        state: directory
        recurse: yes

    - name: Create Grafana datasource file
      template:
        src: ../Roles/Templates/grafana_datasource.yml.j2
        dest: "{{ prometheus_dir }}/grafana/provisioning/datasources/prometheus.yml"
        mode: '0644'

    - name: Create docker-compose.yml (host network)
      template:
        src: ../Roles/Templates/docker-compose.yml.j2
        dest: "{{ prometheus_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Remove existing monitoring containers if any
      command: docker-compose down --remove-orphans
      args:
        chdir: "{{ prometheus_dir }}"
      ignore_errors: yes

    - name: Start monitoring containers
      shell: |
        cd {{ prometheus_dir }}
        docker-compose up -d
      args:
        executable: /bin/bash
