---
- name: Setup Monitoring Stack (Node Exporter + Prometheus + Grafana)
  hosts: web
  become: yes
  vars:
    prometheus_dir: /opt/monitoring
    grafana_admin_password: "ChangeMe123!"
  tasks:

    - name: Install dependencies
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Install Docker Legacy and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create monitoring directory
      file:
        path: "{{ prometheus_dir }}"
        state: directory
        mode: '0755'

    - name: Create Prometheus config
      template:
        src: ../Roles/Templates/prometheus.yml.j2
        dest: "{{ prometheus_dir }}/prometheus.yml"
        mode: '0644'

    - name: Create Grafana provisioning directories
      file:
        path: "{{ prometheus_dir }}/grafana/provisioning/datasources"
        state: directory
        recurse: yes

    - name: Create Grafana datasource file
      template:
        src: ../Roles/Templates/grafana_datasource.yml.j2
        dest: "{{ prometheus_dir }}/grafana/provisioning/datasources/prometheus.yml"
        mode: '0644'

    - name: Create docker-compose.yml (host network)
      template:
        src: ../Roles/Templates/docker-compose.yml.j2
        dest: "{{ prometheus_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Remove existing monitoring containers if any
      command: docker-compose down --remove-orphans
      args:
        chdir: /opt/monitoring
      ignore_errors: yes


    - name: Start monitoring containers
      shell: |
        cd {{ prometheus_dir }}
        docker-compose up -d
      args:
        executable: /bin/bash