name: 🚀 Deploy Fullstack App via Ansible (Auto from Terraform)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-ansible]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Ansible repo
      - name: Checkout Ansible repo
        uses: actions/checkout@v4

      # 2️⃣ Checkout Terraform repo
      - name: Checkout Terraform repo
        uses: actions/checkout@v4
        with:
          repository: Dency-28/Tf-den
          path: Tf-den  # Capital T to match folder

      # 3️⃣ Setup SSH key for Ansible
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYER_NEW }}" > ~/.ssh/deployer.pem
          chmod 600 ~/.ssh/deployer.pem

      # 4️⃣ Disable strict host key checking
      - name: Disable host key checking
        run: |
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      # 5️⃣ Install Terraform and Ansible
      - name: Install Terraform & Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible unzip curl
          curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
          sudo unzip -o terraform.zip -d /usr/local/bin/

      # 6️⃣ Export AWS credentials for Terraform
      - name: Export AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV

      # 7️⃣ Initialize Terraform and get EC2 IP
      - name: Get EC2 Public IP from Terraform
        id: tfoutput
        run: |
          cd Tf-den/terraform_infra
          terraform init -input=false
          terraform apply -auto-approve
          terraform output -raw ec2_public_ip > ec2_ip.txt
          echo "EC2_IP=$(cat ec2_ip.txt)" >> $GITHUB_ENV
          echo "✅ Terraform EC2 IP: $(cat ec2_ip.txt)"

      # 8️⃣ Print EC2 IP for debug
      - name: Print EC2 IP
        run: echo "🌐 EC2 IP is $EC2_IP"

      # 9️⃣ Generate dynamic Ansible inventory
      - name: Generate dynamic inventory
        run: |
          echo "[all]" > inventory.ini
          echo "ec2-instance ansible_host=$EC2_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/deployer.pem" >> inventory.ini
          echo "" >> inventory.ini
          echo "[all:vars]" >> inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3" >> inventory.ini
          echo "✅ Inventory created:"
          cat inventory.ini

      # 🔟 Test Ansible connectivity
      - name: Test Ansible connectivity
        run: ansible all -i inventory.ini -m ping

      # 1️⃣1️⃣ Run all Ansible Playbooks
      - name: Run Ansible Playbooks
        run: |
          ansible-playbook -i inventory.ini Playbooks/install_dependencies.yml
          ansible-playbook -i inventory.ini Playbooks/configure_nginx.yml
          ansible-playbook -i inventory.ini Playbooks/deploy_containers.yml
          ansible-playbook -i inventory.ini Playbooks/env_and_ssl.yml
          ansible-playbook -i inventory.ini Playbooks/rolling_update.yml
