name: Deploy Fullstack App with Ansible

on:
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Start SSH agent and add key from GitHub Secret
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYER_NEW }}

      # 3️⃣ Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update -y
          sudo apt install -y ansible

      # 4️⃣ Test SSH connection using the agent
      - name: Test SSH connection
        run: |
          ansible all -i inventory.ini -m ping

      # 5️⃣ Run Playbooks
      - name: Run Ansible Playbooks
        run: |
          ansible-playbook -i inventory.ini Playbooks/install_dependencies.yml
          ansible-playbook -i inventory.ini Playbooks/configure_nginx.yml
          ansible-playbook -i inventory.ini Playbooks/deploy_containers.yml
          ansible-playbook -i inventory.ini Playbooks/env_and_ssl.yml
          ansible-playbook -i inventory.ini Playbooks/rolling_update.yml
