name: Terraform-Ansible-Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      # 3. Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: terraform-ec2

      # 5. Terraform Plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform-ec2

      # 6. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform-ec2

      # 7. Get EC2 Public IP (clean)
      - name: Get EC2 Public IP
        id: ec2
        run: |
          ip=$(terraform output -raw ec2_public_ip | tr -d '[:space:]')
          echo "EC2_IP=$ip" >> $GITHUB_ENV
          echo "Public IP is $ip"
        working-directory: terraform-ec2

      # 8. Setup SSH Key
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deployer.pem
          chmod 600 ~/.ssh/deployer.pem

      # 9. Install Ansible
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      # 10. Generate dynamic Ansible inventory
      - name: Generate Ansible Inventory
        run: |
          echo "[all]" > inventory.ini
          echo "ec2-instance ansible_host=${{ env.EC2_IP }} ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/deployer.pem" >> inventory.ini
          echo "[all:vars]" >> inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3" >> inventory.ini
          cat inventory.ini

      # 11. Run Ansible Playbook (correct path with capital P)
      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini ansible-phase3-config/Playbooks/deploy_containers.yml
