name: Ansible-Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Phase 3 repo
        uses: actions/checkout@v3
        with:
          path: phase3

      - name: Checkout Phase 1 repo
        uses: actions/checkout@v3
        with:
          repository: Dency-28/Tf-den
          token: ${{ secrets.GH_TOKEN }}
          path: phase1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Disable Host Key Checking
        run: |
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Get EC2 Public IP
        id: ec2
        run: |
          IP=$(terraform -chdir=phase1/terraform_infra output -raw ec2_public_ip)
          if [ -z "$IP" ]; then
            echo "Error: EC2 public IP not found!"
            exit 1
          fi
          echo "EC2_IP=$IP" >> $GITHUB_ENV
          echo "Public IP is $IP"

      - name: Generate Ansible Inventory
        run: |
          echo "[all]" > inventory.ini
          echo "ec2-instance ansible_host=$EC2_IP ansible_user=ec2-user" >> inventory.ini
          echo "[all:vars]" >> inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3" >> inventory.ini
          cat inventory.ini

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini phase3/Playbooks/deploy_containers.yml
