name: Deploy Fullstack App with Ansible

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-ansible]

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup SSH access to EC2
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYER_NEW }}

      # 3️⃣ Add EC2 host to known_hosts (avoid manual approval)
      - name: Disable host key checking
        run: |
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      # 4️⃣ Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update -y
          sudo apt install -y ansible

      # 5️⃣ Display EC2 connectivity check
      - name: Verify SSH Connection
        run: |
          ansible all -i inventory.ini -m ping

      # 6️⃣ Run all Playbooks sequentially
      - name: Run Ansible Playbooks
        run: |
          ansible-playbook -i inventory.ini Playbooks/install_dependencies.yml
          ansible-playbook -i inventory.ini Playbooks/configure_nginx.yml
          ansible-playbook -i inventory.ini Playbooks/deploy_containers.yml
          ansible-playbook -i inventory.ini Playbooks/env_and_ssl.yml
          ansible-playbook -i inventory.ini Playbooks/rolling_update.yml
