name: Deploy Fullstack App with Ansible

on:
  workflow_dispatch:

jobs:
  ansible-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Start SSH agent and add key from secret
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYER_NEW }}

      # 3️⃣ Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update -y
          sudo apt install -y ansible

      # 4️⃣ Debug: List SSH keys in agent
      - name: List SSH keys in agent
        run: |
          ssh-add -l

      # 5️⃣ Verify SSH connection
      - name: Verify SSH Connection with Ansible
        run: |
          ansible all -i inventory.ini -m ping -u ec2-user -vvvv

      # 6️⃣ Run all Playbooks sequentially
      - name: Run Ansible Playbooks
        run: |
          ansible-playbook -i inventory.ini Playbooks/install_dependencies.yml -u ec2-user
          ansible-playbook -i inventory.ini Playbooks/configure_nginx.yml -u ec2-user
          ansible-playbook -i inventory.ini Playbooks/deploy_containers.yml -u ec2-user
          ansible-playbook -i inventory.ini Playbooks/env_and_ssl.yml -u ec2-user
          ansible-playbook -i inventory.ini Playbooks/rolling_update.yml -u ec2-user
