name: 🚀 Deploy Fullstack App via Ansible (Auto from Terraform)

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-ansible]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout both Ansible and Terraform repositories
      - name: Checkout Ansible repo
        uses: actions/checkout@v4

      - name: Checkout Terraform repo
        uses: actions/checkout@v4
        with:
          repository: Dency-28/Tf-den
          path: Tf-den  # ✅ Capital T to match your folder

      # 2️⃣ Setup SSH for EC2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYER_NEW }}

      - name: Disable host key checking
        run: |
          mkdir -p ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      # 3️⃣ Install Terraform and Ansible
      - name: Install Terraform & Ansible
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible unzip curl
          curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
          sudo unzip terraform.zip -d /usr/local/bin/

      # 4️⃣ Initialize Terraform and fetch EC2 IP dynamically
      - name: Get EC2 Public IP from Terraform
        id: tfoutput
        run: |
          cd Tf-den/terraform_infra
          terraform init -input=false
          terraform output -raw ec2_public_ip > ec2_ip.txt
          echo "EC2_IP=$(cat ec2_ip.txt)" >> $GITHUB_ENV
          echo "✅ Terraform EC2 IP: $(cat ec2_ip.txt)"

      # 5️⃣ Print IP for debug
      - name: Print EC2 IP
        run: echo "🌐 EC2 IP is $EC2_IP"

      # 6️⃣ Generate dynamic Ansible inventory
      - name: Generate dynamic inventory
        run: |
          echo "[all]" > inventory.ini
          echo "ec2-instance ansible_host=$EC2_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/deployer.pem" >> inventory.ini
          echo "" >> inventory.ini
          echo "[all:vars]" >> inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3" >> inventory.ini

          echo "✅ Inventory created:"
          cat inventory.ini

      # 7️⃣ Test SSH connectivity
      - name: Test Ansible connectivity
        run: ansible all -i inventory.ini -m ping

      # 8️⃣ Run Ansible Playbooks in sequence (Corrected folder name: Playbooks)
      - name: Run Ansible Playbooks
        run: |
          ansible-playbook -i inventory.ini Playbooks/install_dependencies.yml
          ansible-playbook -i inventory.ini Playbooks/configure_nginx.yml
          ansible-playbook -i inventory.ini Playbooks/deploy_containers.yml
          ansible-playbook -i inventory.ini Playbooks/env_and_ssl.yml
          ansible-playbook -i inventory.ini Playbooks/rolling_update.yml
