name: Ansible-Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Phase 3 repo
        uses: actions/checkout@v3
        with:
          path: phase3

      - name: Checkout Phase 1 repo
        uses: actions/checkout@v3
        with:
          repository: Dency-28/Tf-den
          token: ${{ secrets.GH_TOKEN }}
          path: phase1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOYER_NEW }}

 # 3️⃣ Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
 
      - name: Run Playbooks
        run: |
          ansible-playbook Playbooks/configure_ngnix.yml -i inventory.ini 
          ansible-playbook Playbooks/deploy_containers.yml -i inventory.ini 
          ansible-playbook Playbooks/env_and_ssl.yml -i inventory.ini 
          ansible-playbook Playbooks/install_dependencies.yml -i inventory.ini
          ansible-playbook Playbooks/rolling_update.yml -i inventory.ini 
 